"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { FlaskConical, ArrowRight, Sparkles } from "lucide-react";
import CannedOverview from "@/components/canned-overview";
import { AI_ANSWER_ENABLED } from "@/lib/ai-config";
import { generateAnswer } from "@/lib/ai-client";
import type { OverviewIntent, OverviewLink } from "@/lib/ai-overview";

type Intent = OverviewIntent | { paragraphs: string[]; related: OverviewLink[] };

interface LiveOverviewProps {
  query: string;
  context: string;
  intent: Intent;
}

/**
 * Tries to render a live, model-generated answer via the secured Worker.
 * Until it arrives (and if it fails or is disabled) it shows the instant,
 * static CannedOverview — so there is always an answer and never a hard error.
 */
export default function LiveOverview({ query, context, intent }: LiveOverviewProps) {
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [answer, setAnswer] = useState("");
  const [provider, setProvider] = useState("");

  useEffect(() => {
    if (!AI_ANSWER_ENABLED || !query) return;
    let cancelled = false;
    setStatus("loading");

    generateAnswer(query, context)
      .then((res) => {
        if (cancelled) return;
        setAnswer(res.answer);
        setProvider(res.provider);
        setStatus("done");
      })
      .catch(() => {
        if (!cancelled) setStatus("error");
      });

    return () => {
      cancelled = true;
    };
  }, [query, context]);

  // Disabled, idle, or failed → fall back to the static overview.
  if (!AI_ANSWER_ENABLED || status === "error" || status === "idle") {
    return <CannedOverview intent={intent} />;
  }

  if (status === "loading") {
    return (
      <div className="relative">
        <CannedOverview intent={intent} />
        <div className="absolute top-5 right-6 flex items-center gap-1.5 text-xs text-[#1a73e8]">
          <Sparkles className="w-3.5 h-3.5 animate-pulse" />
          Generating live answer…
        </div>
      </div>
    );
  }

  // status === "done" — render the live answer with a provider attribution.
  return (
    <div className="bg-white border border-[#e0e0e0] rounded-xl p-6 shadow-sm font-sans">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2 text-[#202124]">
          <FlaskConical className="w-5 h-5 text-[#1a73e8]" />
          <span className="text-sm font-bold">AI Overview</span>
        </div>
        <span className="inline-flex items-center gap-1 text-xs text-[#5f6368] bg-[#f1f3f4] px-2.5 py-1 rounded-full">
          <Sparkles className="w-3 h-3 text-[#1a73e8]" />
          via {provider}
        </span>
      </div>

      <div className="space-y-3 text-[15px] leading-7 text-[#202124] whitespace-pre-line">{answer}</div>

      {intent.related.length > 0 && (
        <div className="mt-4 pt-4 border-t border-[#f1f3f4] flex flex-wrap gap-2">
          {intent.related.map((r) => {
            const external = r.url.startsWith("http");
            return (
              <Link
                key={r.url + r.label}
                href={r.url}
                target={external ? "_blank" : "_self"}
                className="inline-flex items-center gap-1 text-sm text-[#1a73e8] bg-[#e8f0fe] hover:bg-[#d2e3fc] px-3 py-1.5 rounded-full transition-colors"
              >
                {r.label}
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            );
          })}
        </div>
      )}

      <p className="mt-4 text-xs text-[#5f6368]">
        Generated by {provider} from this site's content, and may be incomplete.
      </p>
    </div>
  );
}
